version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/javelyn
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/verify_service.sh
      timeout: 300
      runas: ec2-user
