version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region sa-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w5h9t1j4
  build:
    commands:
      - docker build -t synkroflare .
      - docker tag synkroflare:latest public.ecr.aws/w5h9t1j4/synkroflare:latest
  post_build:
    commands:
      - docker push public.ecr.aws/w5h9t1j4/synkroflare:latest
